twilio/video-quickstart-android

- quickstart/build.gradle
Added example of how to reduce apk size by using [APK Splits](https://developer.android.com/studio/build/configure-apk-splits.html).
> Adding apk splits to quickstart

- exampleAdvancedCameraCapturer/src/main/java/com/twilio/video/examples/advancedcameracapturer/AdvancedCameraCapturerActivity.java
- exampleAdvancedCameraCapturer/src/main/res/layout/activity_advanced_camera_capturer.xml
- exampleAdvancedCameraCapturer/src/main/res/layout/picture_image_view.xml
- exampleAdvancedCameraCapturer/src/main/res/values/strings.xml
The picture taken is displayed in a simple `AlertDialog`. I decided against a gallery view because it would require saving images and implementing a `RecyclerView`. Screenshots below.
> Adding example for taking a picture on camera capturer

- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
In multiparty scenario, participant video can be removed even if that participant is still in the room. This causes both remote and local view to be rendered in primary view.
> Check identity before removing participant video

- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
This PR fixes #49. We were not handling participant video tracks correctly. Now the remote participant's video track is added `onConnected` and `onVideoTrackAdded`
> Fixes double rendering issue when re-entering room #49

- exampleAdvancedCameraCapturer/build.gradle
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleScreenCapturer/build.gradle
Including content from [1.0.0-beta10 Changelog](https://www.twilio.com/docs/api/video/changelogs/android#100-beta10-february-24-2017)
Improvements
- Network handoff, and subsequent connection renegotiation is now supported for IPv4 networks.
Bug Fixes
- Fixed a regression introduced in 1.0.0-beta8 where tokens with purely numeric identities caused a crash [#64](https://github.com/twilio/video-quickstart-android/issues/64) [#60](https://github.com/twilio/video-quickstart-android/issues/60)
- Participant identities now support UTF-8
> Updates to 1.0.0-beta10 release

- quickstart/build.gradle
I accidentally did not include quickstart module update in #67 . I updated the module and validated the quickstart flow again.
> Update quickstart module to use 1.0.0-beta10

- build.gradle
- exampleAdvancedCameraCapturer/build.gradle
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleScreenCapturer/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- quickstart/build.gradle
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
From [1.0.0-beta11 changelog](https://www.twilio.com/docs/api/video/changelogs/android#100-beta11-march-6-2017)
Improvements
- Moved `connect` from instance method to static method on `VideoClient` class. Calling the new static `connect` method requires a `Context` in addition to `ConnectOptions` and a `Room.Listener` . `VideoClient` is no longer an object that can be instantiated and an instance is no longer required to connect to a `Room`.
- Moved access token parameter from `VideoClient` constructor to `ConnectOptions.Builder` constructor. 
Connecting to a `Room` before 1.0.0-beta11
// Create VideoClient
VideoClient videoClient = new VideoClient(context, accessToken);
ConnectOptions connectOptions = new ConnectOptions.Builder()
.roomName(roomName)
.localMedia(localMedia)
.build(); …
> Updates for 1.0.0-beta11 release

- exampleAdvancedCameraCapturer/build.gradle
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleScreenCapturer/build.gradle
- quickstart/build.gradle
From [1.0.0-beta13 changelog](https://www.twilio.com/docs/api/video/changelogs/android)
Improvements
- Decreased Room connection time by establishing the signaling connection earlier in the process.
- Removed the final case where we resolve localhost. This also improves connection time to your first Room.
Bug Fixes
- Fixed a regression in 1.0.0-beta12 where a track added event was not raised when the trackId was reused. [#83](https://github.com/twilio/video-quickstart-android/issues/83)
- Fixed crash in `Room#disconnect` when releasing `Participant` media
- Resolved memory corruption issues which could occur in multi-party scenarios.
- Fixed a crash which could occur in signaling stack
> Update to 1.0.0-beta13

- exampleAdvancedCameraCapturer/build.gradle
- exampleAdvancedCameraCapturer/src/main/java/com/twilio/video/examples/advancedcameracapturer/AdvancedCameraCapturerActivity.java
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoCapturer/src/main/java/com/twilio/video/examples/customcapturer/CustomCapturerVideoActivity.java
- exampleCustomVideoRenderer/build.gradle
- exampleCustomVideoRenderer/src/main/java/com/twilio/video/examples/customrenderer/CustomRendererVideoActivity.java
- exampleCustomVideoRenderer/src/main/java/com/twilio/video/examples/customrenderer/SnapshotVideoRenderer.java
- exampleScreenCapturer/build.gradle
- exampleScreenCapturer/src/main/java/com/twilio/video/examples/screencapturer/ScreenCapturerActivity.java
- quickstart/build.gradle
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
Improvements
- Replaced `LocalMedia` class with Track factories for `LocalVideoTrack` and `LocalAudioTrack`
Working with `LocalVideoTrack` and `LocalAudioTrack` before 1.0.0-beta17
// Create LocalMedia
LocalMedia localMedia = LocalMedia.create(context);
LocalVideoTrack localVideoTrack = localMedia.addVideoTrack(true, videoCapturer);
LocalAudioTrack localAudioTrack = localMedia.addAudioTrack(true);
...
// Destroy LocalMedia to free native memory resources
localMedia.release();
Working with `LocalVideoTrack` and `LocalAudioTrack` now
// Create Tracks
LocalVideoTrack localVideoTrack = LocalVideoTrack.create(context, true, videoCapturer);
LocalAudioTrack localAudioTrack = LocalAudioTrack.create(context, true);
...
// Destroy Tracks to free native memory resources
localVideoTrack.release(); …
> Update to 1.0.0-beta17 release

- build.gradle
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
Add permission check in onResume to ensure that we create video track after permissions have been granted. Fixes #112
> Add permission check in onResume

- build.gradle
- exampleAdvancedCameraCapturer/build.gradle
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleScreenCapturer/build.gradle
- quickstart/build.gradle
Improvements
- Improved internal native Room operations.
- Improved `ScreenCapturer` performance by enabling capturing to a texture.
- Added new error code for case when participant gets disconnected because of duplicate participant joined the room. 
Bug Fixes
- Fixed issue adding audio/video tracks quickly while connected to a room [#90](https://github.com/twilio/video-quickstart-android/issues/90)
> Update for 1.0.1 release

- exampleAdvancedCameraCapturer/build.gradle
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleScreenCapturer/build.gradle
- exampleVideoInvite/build.gradle
- quickstart/build.gradle
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/util/CameraCapturerCompat.java
Updated each module to `1.1.0` and added `CameraCapturerCompat` to quickstart module. This class uses camera 1 or camera 2 API depending on device compatibility. Changelog entry in following section.
---
Improvements
- Moved signaling network traffic to port 443. 
- Added `Camera2Capturer`. `Camera2Capturer` uses `android.hardware.camera2` to implement 
a `VideoCapturer`. `Camera2Capturer` does not yet implement `takePicture` and the ability to modify 
camera parameters once `Camera2Capturer` is running.
Create `LocalVideoTrack` with `Camera2Capturer`
// Check if device supports Camera2Capturer 
if (Camera2Capturer.isSupported(context)) {
// Use CameraManager.getCameraIdList() for a list of all available camera IDs
String cameraId = "0";
Camera2Capturer.Listener camera2Listener = new …
> 1.1.0 release

- exampleAdvancedCameraCapturer/build.gradle
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleScreenCapturer/build.gradle
- exampleVideoInvite/build.gradle
- quickstart/build.gradle
Bug Fixes
- Fixed bug in `VideoConstraints` logic where valid VideoCapturer video formats were ignored due to very strict checking of aspect ratios in WebRTC
- Fixed bug in Logger.java where setting certain LogLevel's did not print error logs 
- Fixed bug in `LocalVideoTrack` where FPS check was incorrectly marking a constraint as incompatible. [#127](https://github.com/twilio/video-quickstart-android/issues/127)
> Update to 1.1.1 release

- exampleAdvancedCameraCapturer/build.gradle
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleScreenCapturer/build.gradle
- exampleVideoInvite/build.gradle
- quickstart/build.gradle
Features
- The SDK now uses TLS 1.2 in favor of TLS 1.0 to connect to Twilio’s servers.
Improvements
- Deprecated `LocalParticipant#release`. This method is not meant to be called and is now a 
no-op until it is removed in `2.0.0-preview1` release. [#132](https://github.com/twilio/video-quickstart-android/issues/132)
- Added more checks and logging to `CameraCapturer` to help identify cases when the camera service cannot be reached. [#126](https://github.com/twilio/video-quickstart-android/issues/126)
- Changed `getSupportedFormats` for `CameraCapturer`, `ScreenCapturer`, and `Camera2Capturer` to 
be `synchronized`.
Bug Fixes
- Fixed timing issue where camera was not always available after a video track was released. [#126](https://github.com/twilio/video-quickstart-android/issues/126)
> Update to 1.2.0

- exampleAdvancedCameraCapturer/build.gradle
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleScreenCapturer/build.gradle
- exampleVideoInvite/build.gradle
- exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java
- quickstart/build.gradle
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
Improvements
- Calling `Participant#setListener` with `null` is no longer allowed. 
Bug Fixes
- Removed reference to `LocalMedia` in `CameraCapturer` javadoc.
- Fixed race condition that could result in track events not being raised.
> 1.2.2 release

- README.md
- exampleAdvancedCameraCapturer/build.gradle
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleScreenCapturer/build.gradle
- exampleVideoInvite/build.gradle
- exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java
- quickstart/build.gradle
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
Features
- Added `EncodingParameters` which constrains how much bandwidth is used to share audio and 
video. This object has been added to `ConnectOptions` and can also be set on `LocalParticipant` 
after joining a `Room`.
- Added two static `create` methods to `LocalAudioTrack` and `LocalVideoTrack` that allow creating
named tracks. The following snippet demonstrates how to create a video track named "screen".
LocalVideoTrack screenVideoTrack = LocalVideoTrack.create(context, 
true, 
screenCapturer, 
"screen"); 
- Moved `getTrackId` from `Track` to `LocalAudioTrack` and `LocalVideoTrack`.
- Added `AudioCodec` and `VideoCodec` as part of the new codec preferences API. Audio and video
codec preferences can be set in `ConnectOptions`. The following snippet
demonstrates how to prefer the …
> 2.0.0-preview1 release

- quickstart/build.gradle
- quickstart/src/main/AndroidManifest.xml
- quickstart/src/main/java/com/twilio/video/quickstart/activity/SettingsActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/dialog/Dialog.java
- quickstart/src/main/res/menu/menu_video_activity.xml
- quickstart/src/main/res/values/strings.xml
- quickstart/src/main/res/values/styles.xml
- quickstart/src/main/res/xml/settings.xml
This PR adds a settings screen that allows user to change the preferred audio and video codec. If the device does not support H264, the preference will be removed from the settings as an option. Validated H264 usage with Galaxy S5 and Nexus 6. Validated Isac with Galaxy S5 and Asus Zenfone II.
Screenshots
> Codec Preferences

- quickstart/src/main/java/com/twilio/video/quickstart/activity/SettingsActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
- quickstart/src/main/res/layout/preference_dialog_number_edittext.xml
- quickstart/src/main/res/values/strings.xml
- quickstart/src/main/res/xml/settings.xml
Add sender bandwidth constraints. Validated various bitrates on Nexus 6, Galaxy S5, and Nexus 9 as well as updating the EncodingParameters via `LocalParticipant.setEncodingParameters`.
Screenshots
> Sender Bandwidth Constraints

- build.gradle
####1.3.1
Improvements
- Fixed case on some devices where `CameraCapturer` incorrectly reported a failure to close the 
camera.
- Improved echo cancellation on Nexus 6P and Nexus 6 by enabling hardware echo canceller and disabling OpenSL ES.
> Update to Video Android 1.3.1

- README.md
- build.gradle
- exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
Improvements
- Upgraded to Android Oreo from Nougat
Bug Fixes
- Fixed case on some devices where `CameraCapturer` incorrectly reported a failure to close the 
camera.
- Improved echo cancellation on Nexus 6P and Nexus 6 by enabling hardware echo canceller and disabling OpenSL ES.
- Fixed crash disconnecting from `Room` that has not connected [#116](https://github.com/twilio/video-quickstart-android/issues/116)
> 2.0.0 preview3 release

- build.gradle
Improvements
- Twilio CDN no longer hosts the Video Android aar artifacts or Javadocs
**Accessing Artifacts**
If you are downloading Video Android SDK artifacts from the Twilio CDN then there are two 
options available moving forward.
1. Follow our [Downloading Video SDKs Guide for Android](https://www.twilio.com/docs/api/video/download-video-sdks#android-sdk).
2. Download the artifacts [directly from Bintray](https://bintray.com/twilio/releases/video-android#files/com/twilio/video-android).
**Viewing Javadocs**
All Javadocs back to `1.0.0-preview1` are now hosted on [Github Pages](https://pages.github.com/) 
with the following URL scheme. `https://twilio.github.io/twilio-video-android/docs/{version}`
- To view `1.3.7` Javadocs go to …
> Update to 1.3.7

- exampleVideoInvite/src/main/res/layout/content_video.xml
- quickstart/src/main/res/layout/content_video.xml
This change should alleviate any issues developers are having with using `VideoView#setVideoScaleType` as mentioned in #197 
**Before**
**After**
> Update primary video view to wrap content

- build.gradle
Improvements
- Updated javadoc to include note about `VideoView#setVideoScaleType`. Scale type will only
be applied to dimensions defined as `WRAP_CONTENT` or a custom value. Setting a width or height to 
`MATCH_PARENT` results in the video being scaled to fill the maximum value of the dimension.
- Add warning log when calling `setVideoScaleType` when width or height is set to `MATCH_PARENT`
> Update to 1.3.8

- build.gradle
Improvements
- `LocalDataTrack` name is no longer provided via static `create` method argument. DataTrack names
are now provided via `DataTrackOptions`. Reference snippets below:
Creating a `LocalDataTrack` with name _before_ `2.0.0-preview6`
String dataTrackName = "data";
LocalDataTrack localDataTrack = LocalDataTrack.create(context, dataTrackName);
Creating a `LocalDataTrack` with name _after_ `2.0.0-preview6`
String dataTrackName = "data";
DataTrackOptions dataTrackOptions = new DataTrackOptions.Builder()
.name("data")
.build();
LocalDataTrack localDataTrack = LocalDataTrack.create(context, dataTrackOptions);
- Updated javadoc to include note about `VideoView#setVideoScaleType`. Scale type will only
be applied to dimensions defined as `WRAP_CONTENT` or a custom value. Setting a width …
> 2.0.0 preview6

- build.gradle
- exampleDataTrack/src/main/java/com/twilio/video/examples/datatrack/DataTrackActivity.java
- exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
Features
- Added the following callbacks to `RemoteParticipant.Listener`
- `onAudioTrackSubscriptionFailed` - Notifies listener that an audio track could not be 
subscribed to.
- `onVideoTrackSubscriptionFailed` - Notifies listener that a video track could not be 
subscribed to.
- `onDataTrackSubscriptionFailed` - Notifies listener that a data track could not be 
subscribed to.
- Added `trackSid` to `BaseTrackStats`.
Bug Fixes
- Removed public `getEncodingOptions` method from `ConnectOptions`.
> Update examples for 2.0.0-preview8 release

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
Improvements
- Improved internal logic for retrieving ice servers and resolving outbound DNS.
Bug Fixes
- ICE URIs using the turns and stuns scheme are now supported.
The SDK will now use turns by default if turn is enabled for your Room.
- Resolved a condition where ICE candidates might not be applied in Peer-to-Peer Rooms.
- Quieted unnecessary warning logs when preferring codecs.
- Fixed a bug where onDisconnected was not getting invoked due to a race condition between a
network handover and a user initiated disconnect call.
> 2.0.0 beta3 Release

- quickstart/src/main/java/com/twilio/video/quickstart/activity/SettingsActivity.java
Arrays.asList: Returns a fixed-size list backed by the specified array.
not remove().
- codecEntries.remove(H264Codec.NAME);
so, fix Arrays.asList to Collections.addAll.
> fix Arrays.asList to Collections.addAll

- README.md
As noted in an email to existing customers in early April, due to a phased roll out of certain SSL certificates, these versions will stop working after September 18, 2018.
> Deprecation notice for versions 1.0.0-beta10 and earlier

- build.gradle
Improvements
- Updated Android Gradle Plugin version to `3.1.0` and Gradle version to `4.4`
- Initial Connect message now includes Client version metadata.
Bug Fixes
- Fixed a bug where the SDK hangs if DNS resolution fails and the user does not initiate disconnect.
- The signaling Client no longer logs access tokens.
- Fixed a rare internal SDK teardown crash.
- Resolved an issue where the signaling Client could send too many UPDATE messages, or use too many
CPU cycles and disconnect from a Room.
> 1.3.15  Release

- README.md
- build.gradle
- exampleAdvancedCameraCapturer/build.gradle
- exampleAdvancedCameraCapturer/src/main/java/com/twilio/video/examples/advancedcameracapturer/AdvancedCameraCapturerActivity.java
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleCustomVideoRenderer/src/main/java/com/twilio/video/examples/customrenderer/CustomRendererVideoActivity.java
- exampleCustomVideoRenderer/src/main/java/com/twilio/video/examples/customrenderer/SnapshotVideoRenderer.java
- exampleDataTrack/build.gradle
- exampleDataTrack/src/main/java/com/twilio/video/examples/datatrack/CollaborativeDrawingView.java
- exampleDataTrack/src/main/java/com/twilio/video/examples/datatrack/DataTrackActivity.java
- exampleScreenCapturer/build.gradle
- exampleVideoInvite/build.gradle
- exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java
- quickstart/build.gradle
- quickstart/src/main/java/com/twilio/video/quickstart/activity/SettingsActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
- quickstartKotlin/build.gradle
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
Improvements
- Upgraded to WebRTC 67.
- Upgraded to Java 8. Add the following snippet to your `build.gradle` to enable Java 8
features required to build the 3.x Video Android SDK:
android {
compileOptions {
sourceCompatibility 1.8
targetCompatibility 1.8
}
}
- Added @Nullable and @NonNull to all public API fields, methods, and interfaces.
- Updated internal capturer pipeline for `CameraCapturer`, `ScreenCapturer`, and `Camera2Capturer`.
- Upgraded to Android NDK 16.
---
Quickstart Updates
- Upgraded modules to use Java 8.
> Update to 3.0.0-preview1

- build.gradle
Features
- Added flag to IceOptions `abortOnIceServerTimeout` that tells the client whether to continue or abort connecting to a Room when Ice fails to connect.
- Added parameter to IceOptions `iceServersTimeout` that allows control of the timeout period when trying to retrieve Ice servers.
- Added `VideoTextureView`. `VideoTextureView` is similar to `VideoView` but subclasses `TextureView` instead of `SurfaceView`. Unlike SurfaceView, TextureView does not create a separate window but behaves as a regular View. This key difference allows a TextureView to be moved, transformed, animated, etc. For more see the [TextureView documentation](https://developer.android.com/reference/android/view/TextureView.html). If you were previously using [this …
> Update to 2.2.0 release

- build.gradle
Improvements
- Adding a null video/audio codec to `ConnectOptions` will now throw an exception
- Switched CI provider for build, test, and release pipeline.
> Update to 2.2.1

- build.gradle
- exampleDataTrack/src/main/java/com/twilio/video/examples/datatrack/DataTrackActivity.java
- exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
Enhancements
- The signaling Client has been updated to support version 2 of the Room Signaling Protocol (RSP).
- Added ECS debugging support at the signaling layer that will help in troubleshooting ice server related issues.
- Introduced a safer threading model in the signaling layer that prevents occasional crashes and missing Track subscription events.
- The SDK no longer waits for pending events when closing a PeerConnection speeding up the teardown process.
- Moved `RoomState` enum to `Room.State`.
- `onDisconnected` will now return a unique error code when the Room is completed via the REST API.
Bug Fixes
- The signaling Client is more lenient when encountering unexpected RSP messages.
- Resolved a scenario where an ICE restart could be ignored after experiencing signaling glare. …
> Upgrade to 3.0.0-preview3

- build.gradle
- `3.0.0-preview3` has been promoted to `3.0.0-beta1`. The `3.0.0` API is now final and will only receive bug fixes and improvements until `3.0.0` is officially released.
Enhancements
- The signaling Client has been updated to support version 2 of the Room Signaling Protocol (RSP).
- Added ECS debugging support at the signaling layer that will help in troubleshooting ice server related issues.
- Introduced a safer threading model in the signaling layer that prevents occasional crashes and missing Track subscription events.
- The SDK no longer waits for pending events when closing a PeerConnection speeding up the teardown process.
- Moved `RoomState` enum to `Room.State`.
- `onDisconnected` will now return a unique error code when the Room is completed via the REST API.
Bug Fixes
- The …
> Upgrade to 3.0.0-beta1

- build.gradle
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
`3.0.0-beta1` has been promoted to `3.0.0`. The `3.x` SDK is now Generally Available (GA). The `1.x` and `2.x` Video Android SDK remain GA but will only receive critical bug fixes moving forward.
This PR also includes merge from master in preparation for a 3.x -> master merge.
> 3.0.0 Release

- build.gradle
3.1.0
Improvements
- Added `IceCandidatePairStats` to `StatsReport` which gives insight into local and remote ice candidates
- Reduced signaling traffic in Group Rooms when communicating with an ICE-lite agent.
Bug Fixes
- Fixed a bug where the client could send additional ICE candidates after signaling the end of candidates, or mark candidates with a username from a future offer.
Known issues
- The SDK is not side-by-side …
> Update to Video Android 3.1.0

- build.gradle
Improvements
- Added `IceCandidateStats` to `StatsReport` which gives insight into individual ice candidates
- Removed forced ice-restart when synced responses are processed
- Improved the detection of, and recovery from media connection failures. Worst case recovery times have been reduced by up to 10 seconds.
- Added handle to native audio track. This will assist developers when using advanced features like audio track sink.
Known issues
- Participant disconnect event can take up to 120 seconds to occur [#80](https://github.com/twilio/video-quickstart-android/issues/80) …
> Update to video android 3.2.0

- build.gradle
Bug Fixes
- Fixed ICE connection failure after multiple network handovers
Known issues
- Codec preferences do not function correctly in a hybrid codec Group Room with the following
codecs:
- ISAC
- PCMA
- G722
- VP9
| --------------- | --------------- …
> Release 3.2.1

- build.gradle
Improvements
- Fix Screenshare being negotiated as simulcast without the client actually using simulcast.
Known issues
- Codec preferences do not function correctly in a hybrid codec Group Room with the following
codecs:
- ISAC
- PCMA
- G722
- VP9
Size Report
| ABI             | APK Size …
> Upgrade to Video Android 3.2.2

- build.gradle
- exampleDataTrack/src/main/java/com/twilio/video/examples/datatrack/DataTrackActivity.java
- exampleDataTrack/src/main/res/layout/activity_data_track.xml
- exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java
- exampleVideoInvite/src/main/res/layout/content_video.xml
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
- quickstart/src/main/res/layout/content_video.xml
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
- quickstartKotlin/src/main/res/layout/content_video.xml
Improvements
- Added new state `Reconnecting` to `Room.State` and new callbacks `onReconnecting`, `onReconnected` to `Room.Listener`. When the `LocalParticipant` experiences a network interruption in signaling or media, the room will transition to `Reconnecting` and `Room.Listener` will notify the developer of this new state via `onReconnecting`. If the connection is successfully restored, `Room.Listener` will notify the developer via `onReconnected`. However, if the connection could not be reestablished `Room.Listener` will notify the developer via `onDisconnected`.
- Added and updated public API nullability annotations.
- Changed `OpusCodec.NAME` and `IsacCodec.NAME` to lowercase
Add Simple reconnecting UI. Screenshot below.
> Update to 4.0.0 Release

- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
#383 found that when receiving and answering a phone call audio would be routed to the handset after hanging up. This PR addresses #383 by forcing audio routing through the speaker. 
- Added `audioManager.setSpeakerphoneOn(true);` to `onResume`. 
- Tested locally and could no longer reproduce the issue.
> Cache audio routing 

- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
#383 found that when receiving and answering a phone call audio would be routed to the handset after hanging up. This PR addresses #383 by forcing audio routing through the speaker. 
- `isSpeakerPhoneEnabled` is used to cache the speaker phone audio route setting
- `audioManager.isSpeakerphoneOn = isSpeakerPhoneEnabled` is applied in `onResume`.
- Tested locally and could no longer reproduce the issue.
> Add speakerphone routing work around for Kotlin

- build.gradle
Bug Fixes
- `Room.getStats()` will raise a callback to the provided `StatsObserver` if called while `Room.getState() == Room.State.RECONNECTING`.
- Fixed a crash related to stats gathering which could occur when insights reporting is enabled.
- Fixed a crash related to media state summarization which could occur when disconnecting from a Room.
- Fixed a crash related to stats gathering which could occur in the media monitor component.
Known issues
- Participant disconnect event can take up to 120 seconds to occur [#80](https://github.com/twilio/video-quickstart-android/issues/80) …
> Video Android 4.0.1

- build.gradle
Bug Fixes
- Fixed bug in `Camera2Capturer.switchCamera` which resulted in `onCameraSwitched` being invoked with a `null` camera ID [#379](https://github.com/twilio/video-quickstart-android/issues/379)
Known issues
- Codec preferences do not function correctly in a hybrid codec Group Room …
> Video Android 4.0.2

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
I've updated the versions of Gradle, Android Gradle Plugin and Kotlin. Therefore, the project can be opened with the current stable Android Studio release (3.2.2 as of today) without any warning.
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.
> Gradle, Android Gradle Plugin and Kotlin version bump

- build.gradle
Improvements
- Added the `AudioSink` interface. When added to a `LocalAudioTrack` or `RemoteAudioTrack`, developers will receive a callback with the raw audio byte buffer from each audio frame. The example below demonstrates adding an `AudioSink` to a `LocalAudioTrack`.
```
AudioSink audioSink = (audioSample, encoding, sampleRate, channels) -> {
Log.v("AudioSink", "Received audio frame");
};
localAudioTrack.addSink(audioSink);
```
The `AudioSink` can then be removed with the following code.
```
localAudioTrack.removeSink(audioSink);
```
Known issues
- Participant disconnect event can take up to 120 seconds to occur …
> Video Android 4.1.0

- build.gradle
Improvements
- Fixed various Lint errors / warnings.
Known issues
- Codec preferences do not function correctly in a hybrid codec Group Room with the following
codecs:
- ISAC
- PCMA
- G722
- VP9
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by …
> Video Android 4.1.1

- build.gradle
Bug Fixes
- Fixed stuck aspect ratio when switching orientations with `ScreenCapturer`.
- Fixed a bug where media reconnection might fail when the loopback interface is mistakenly chosen as a preferred network interface.
Known issues
- Codec preferences do not function correctly in a …
> Update to Video Android 4.1.2

- build.gradle
Improvements
- Added field `enableAutomaticSubscription` to `ConnectOptions`. `enableAutomaticSubscription` toggles automatic track subscription. If set to `false`, the `LocalParticipant` will receive notifications of track publish events, but will not automatically subscribe to them. If
set to `true`, the `LocalParticipant` will automatically subscribe to tracks as they are published. If unset, the default is `true`. Note: This feature is only available for Group Rooms. Toggling the flag in a P2P room does not modify subscription behavior.
Known issues
- Participant disconnect event can take up to 120 seconds to occur …
> Video Android 4.2.0

- build.gradle
API Changes
- Implemented the Dominant Speaker functionality for Group Rooms. To enable the dominant speaker functionality, set the `ConnectOptions.dominantSpeakerEnabled` property to `true` when connecting to a Group Room. To determine the current dominant speaker, query the `Room.getDominantSpeaker()` method. When there is no dominant speaker, the `ConnectOptions.dominantSpeakerEnabled` property was set to `false` or when using a Peer-to-Peer room, the `Room.getDominantSpeaker()` method will always return `null`. When there is a dominant speaker, the `Room.getDominantSpeaker()` method will return the appropriate `RemoteParticipant`. Implementing `Room.Listener.onDominantSpeakerChanged()` method on your `Room.Listener` will allow you to receive callbacks when the dominant speaker in a …
> Video Android 4.3.0: Dominant Speaker

- build.gradle
Improvements
- The Participant's signaling connection now conforms to Twilio's [TLS & Cipher Suite Policy](https://support.twilio.com/hc/en-us/articles/360007724794-Notice-Twilio-REST-API-s-TLS-and-Cipher-Suite-Security-Changes-for-June-2019). Support for TLS versions older than 1.2 has been removed.
- Adjusted the buffer sizes used for signaling messages to reduce network fragmentation.
- Setting `video::LogModule::kSignaling` enables logging of low-level connection events.
Bug Fixes
- WebSocket errors are handled immediately, rather than waiting for a timeout to occur.
- Handle rare exceptions when constructing a WebSocket.
Known issues
- Future 5.0.0-beta releases will reduce the number of round-trips required to connect to a Room.
- In rare cases, the SDK might timeout during a TCP …
> 5.0.0-beta2

- quickstart/src/main/java/com/twilio/video/quickstart/util/CameraCapturerCompat.java
This PR introduces a fix for the crash experienced on the Samsung S10 as described in this [issue](https://github.com/twilio/video-quickstart-android/issues/431). This is a temporary work around and a long term solution is currently in development.
> GSDK-1987: Provide workaround for S10 camera crash

- build.gradle
Bug Fixes
- Fixed updating `CameraCapturer.State` when error occurs.
Known issues
- Codec preferences do not function correctly in a hybrid codec Group Room with the following
codecs:
- ISAC
- PCMA
- G722
- VP9
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might …
> Video Android 4.3.1

- .circleci/config.yml
- build.gradle
- exampleAdvancedCameraCapturer/build.gradle
- exampleCustomVideoCapturer/build.gradle
- exampleCustomVideoRenderer/build.gradle
- exampleMultipartyVideo/src/main/java/com/twilio/examplemultipartyvideo/MultiPartyActivity.java
- exampleScreenCapturer/build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- quickstart/build.gradle
The Dominant Speaker Detection API sends events to your application every time the dominant speaker changes. You can use those events to improve the end user's experience by, for example, highlighting which participant is currently talking.
The Dominant Speaker Detection API is only available for Group Rooms.  To enable dominant speaker detection, set the `ConnectOptions.dominantSpeakerEnabled` property to `true`. Use `Room.getDominantSpeaker()` to determine the current dominant speaker. Implement `Room.Listener.onDominantSpeakerChanged()` method to receive callbacks when the dominant speaker changes.
For more information, refer to the [API docs](https://twilio.github.io/twilio-video-android/docs/5.0.0-beta3/) and to the [dominant speaker …
> Update for 5.0.0-beta3 release

- README.md
- build.gradle
* Programmable Video Android SDK 5.0.1 [[bintray]](https://bintray.com/twilio/releases/video-android/5.0.1), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.0.1/)
- Fixed a deadlock that could occur when destroying a `Room` without waiting for `Room.Listener.onDisconnected(...)` to arrive.
- Fixed a crash which could occur when disconnecting from a  `Room` with dominant speaker enabled.
Size Report
| universal       | 22.9MB          |
| armeabi-v7a     | 5MB             |
| …
> Use Video Android SDK 5.0.1 release

- build.gradle
- exampleCustomVideoRenderer/src/main/java/com/twilio/video/examples/customrenderer/SnapshotVideoRenderer.java
- quickstart/src/main/java/com/twilio/video/quickstart/activity/SettingsActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/util/CameraCapturerCompat.java
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/CameraCapturerCompat.kt
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/SettingsActivity.kt
* Programmable Video Android SDK 5.1.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.1.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.1.0/)
Improvements
- The SDK can now be compiled alongside another WebRTC based dependency. Please perform the
following steps to properly upgrade to `5.1.0`
- Modify the classpath of any java files used from `org.webrtc.*` to `tvi.webrtc.*`. Calling
APIs to any class in `org.webrtc.*` will have no effect within the Video SDK.
- Perform the following modifications to your proguard file when compiling the Video SDK for a
release build with obfuscation.
- Change `-keep class org.webrtc.** { *; }` to `-keep class tvi.webrtc.** { *; }`
- Change `-dontwarn org.webrtc.**` to `-dontwarn tvi.webrtc.**`
Known issues
- …
> Update to 5.1.0 release

- build.gradle
- exampleScreenCapturer/src/main/AndroidManifest.xml
- exampleScreenCapturer/src/main/java/com/twilio/video/examples/screencapturer/ScreenCapturerActivity.java
- exampleScreenCapturer/src/main/java/com/twilio/video/examples/screencapturer/ScreenCapturerManager.java
- exampleScreenCapturer/src/main/java/com/twilio/video/examples/screencapturer/ScreenCapturerService.java
Android Q now requires developers to specify a [foreground service](https://developer.android.com/about/versions/10/features#fg-service-types) when using the MediaProjection API. Implemented `ScreenCapturerManager` and `ScreenCapturerService`, that start/stop foreground service before/after screen capture.
> GSDK-1981 : Fix  Screen Capturer crash targeting Android Q

- build.gradle
* Programmable Video Android SDK 5.1.1 [[bintray]](https://bintray.com/twilio/releases/video-android/5.1.1), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.1.1/)
Enhancements
- Reduced bandwidth usage for Insights reporting by up to 75%.
- Data track per-message size limit has been increased to 64 KB.
Bug Fixes
- Fixed a crash which could occur when destroying a Room while the TCP handshake for the
signaling connection is in progress.
- Fixed intermittent crash when sending data on a data track while in the process of closing the
track due to remote participant disconnect.
Known issues
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by Participants. As a result, tracks published after a `Room.State.RECONNECTED` event might not be …
> Update to 5.1.1

- build.gradle
- exampleMultipartyVideo/src/main/java/com/twilio/examplemultipartyvideo/MultiPartyActivity.java
- exampleMultipartyVideo/src/main/java/com/twilio/examplemultipartyvideo/ParticipantView.java
- exampleMultipartyVideo/src/main/res/layout/activity_video.xml
- exampleMultipartyVideo/src/main/res/layout/participant_container_layout.xml
- exampleMultipartyVideo/src/main/res/values/strings.xml
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
This PR adds Remote Participant Network Quality functionality to the Multiparty example application.
- Consume Video Android 5.2.0
- Removed the status info text to be more consistent with iOS
- Added `networkQualityLevelImageView ` to `ParticipantView`
- Removed `networkQualityLevelImage` from `MultiPartyActivity` for the local participant in favor of using the one in the local participants `ParticipantView`
- Only show the network quality indicator when network quality levels are received for a participant to be consistent with the iOS app.
- Added nullability annotations to `RemoteParticipant.Listener`.
- Wired up the `RemoteParticipant.Listener.onNetworkQualityLevelChanged` for handling remote participant network quality events.
- Testing across Pixel 3a, Pixel 2, iPhone X and iPhone …
> Update to 5.2.0: Remote Participant Network Quality

- README.md
Add video app link to readme like https://github.com/twilio/video-quickstart-js.
> AHOYAPPS-476: Add video app link to readme

- build.gradle
Update Version to latest release 5.3.0
* Programmable Video Android SDK 5.3.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.3.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.3.0/)
Features
- Implemented a boolean Connect Option `enableIceGatheringOnAnyAddressPorts` that allows gathering of ICE candidates from "any address" ports. The default value is false. Setting it to true will allow applications to work in a wider set of VPN environments.
Bug Fixes
- Fixed a crash when attempting to unpublish a local track that was not previously published. [#447](https://github.com/twilio/video-quickstart-android/issues/447)
Known issues
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by Participants. As a result, tracks …
> Update SDK version to 5.3.0

- build.gradle
- exampleVideoInvite/src/main/res/layout/content_video.xml
- quickstart/src/main/res/layout/content_video.xml
- quickstartKotlin/src/main/res/layout/content_video.xml
* Programmable Video Android SDK 5.4.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.4.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.4.0/)
Enhancements
- Reduced the SDK size. The table below highlights the updated app size impact.
| ABI             | App Size Impact 5.3.0 | App Size Impact 5.4.0 |
| --- | --- | --- |
| universal       | 22.9MB | 21.8MB          |
| armeabi-v7a     | 5MB | 4.8MB           |
| arm64-v8a       | 5.9MB | 5.6MB           |
| x86             | 6.2MB | 6MB             |
| x86_64          | 6.4MB | 6MB             |
Bug Fixes
- Fixed [an issue](https://github.com/twilio/video-quickstart-android/issues/487) integrating the SDK with applications that contain an attribute of `scaleType`, `mirror`, or `overlaySurface`. These …
> Update to Video Android 5.4.0

- build.gradle
* Programmable Video Android SDK 5.5.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.5.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.5.0/)
Enhancements
- Added `updateCaptureRequest` to `Camera2Capturer`. This API allows developers to update the [CaptureRequest](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest) of an ongoing `Camera2Capturer` session. Reference the following snippet as an example of how to turn the flash on for the `Camera2Capturer`.
```
camera2Capturer.updateCaptureRequest(
new CaptureRequestUpdater() {
@Override
public void apply(@NotNull CaptureRequest.Builder captureRequestBuilder) {
captureRequestBuilder.set(CaptureRequest.FLASH_MODE, CaptureRequest.FLASH_MODE_TORCH);
}
});
```
Known issues
- …
> Update to Video Android 5.5.0

- build.gradle
* Programmable Video Android SDK 5.5.1 [[bintray]](https://bintray.com/twilio/releases/video-android/5.5.1), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.5.1/)
Bug Fixes
- Fixed an occasional native crash when disconnecting from a Room.
- Fixed a bug when establishing a signaling WebSocket that might cause only one address family (IPv4 or IPv6) to be tried.
- Publish stats reports every 10 seconds and active ICE candidate pair messages every 20 seconds. Previously both were reported every 4 seconds.
Known issues
Size Report
| ABI             | …
> Update to Video Android 5.5.1

- build.gradle
* Programmable Video Android SDK 5.6.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.6.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.6.0/)
Enhancements
- A subset of Android devices provide an [OpenSLES](href="https://www.khronos.org/opensles/) implementation. Although more efficient, the use of OpenSLES occasionally causes echo. As a result, the Video SDK now disables OpenSLES by default unless explicitly enabled. To enable OpenSLES, execute the following before invoking `Video.connect(...)` : `tvi.webrtc.voiceengine.WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage(false)`.
Known issues
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by Participants. As a result, tracks published after a …
> Update to Video Android 5.6.0

- README.md
- build.gradle
This PR updates the trouble shooting audio section with the updated OpenSLES policy as of Video Android SDK 5.6.0. Additionally, the AudioSwitch version was bumped.
> Update troubleshooting audio section

- build.gradle
Upgraded audioswitch to 0.1.3
Bug Fixes
- Fixed crash by adding a default bluetooth device name.
> Upgrade audioswitch to 0.1.3

- build.gradle
* Programmable Video Android SDK 5.7.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.7.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.7.0/)
Enhancements
- Previously, the Video Android SDK would fail connection attempts if the signaling server was busy with too many requests. Now, it will try again after a server specified backoff period either until it is successfully connected or the server asks it to stop trying. In this case, the `onConnectFailure` method is called with `SIGNALING_SERVER_BUSY_EXCEPTION`.
```.java
@Override
public void onConnectFailure(@NonNull Room room, @NonNull TwilioException twilioException) {
if (twilioException.getCode() == TwilioException.SIGNALING_SERVER_BUSY_EXCEPTION) {
Log.d("RoomListener", "Twilio's signaling server …
```
> Update to Video Android 5.7.0

- build.gradle
* Programmable Video Android SDK 5.8.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.8.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.8.0/)
You can now configure how your available downlink bandwidth will be distributed among your subscribed RemoteVideoTracks by using a new optional ConnectOptions parameter bandwidthProfile. For more details and best practices, visit the [Network Bandwidth Profile API guide](https://www.twilio.com/docs/video/tutorials/using-bandwidth-profile-api). Here is a brief example:
```java
Room room = Video.connect(context, new ConnectOptions.Builder(accessToken)
.bandwidthProfile(new BandwidthProfileOptions(new VideoBandwidthProfileOptions.Builder()
// Minimum subscribe priority of Dominant Speaker's RemoteVideoTracks …
```
> Update to Video Android 5.8.0

- gradle.properties
Remove `android.enableDexingArtifactTransform.desugaring=false` as there was a fix introduced in the Android Gradle Plugin version [3.6.0-beta05](https://issuetracker.google.com/issues/140508065#comment28) in which the flag is no longer needed.
> Remove artifact desugaring flag

- build.gradle
- exampleAdvancedCameraCapturer/gradle.properties
- exampleAudioSink/gradle.properties
- exampleCustomVideoCapturer/gradle.properties
- exampleCustomVideoRenderer/gradle.properties
- exampleDataTrack/gradle.properties
- exampleScreenCapturer/gradle.properties
- exampleVideoInvite/gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- quickstart/gradle.properties
- quickstartKotlin/gradle.properties
* Programmable Video Android SDK 5.8.1 [[bintray]](https://bintray.com/twilio/releases/video-android/5.8.1), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.8.1/)
Bug Fixes
- Fixed the issue where unpublishing and then republishing a `LocalVideoTrack` using VP8 simulcast does not complete.
Maintenance
- Upgraded to Android Gradle Plugin 4.0.0 and Gradle 6.1.1
- Upgraded the SDK to use AndroidX. Please follow the [Migrating to AndroidX](https://developer.android.com/jetpack/androidx/migrate) instructions to consume Video Android 5.8.1 in your app.
Known issues
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by Participants. As a result, tracks published after a `Room.State.RECONNECTED` event might not be subscribed to by a …
> Update to Video Android 5.8.1

- build.gradle
* Programmable Video Android SDK 5.9.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.9.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.9.0/)
Enhancements
- Reduced connection times by acquiring IceServers during the initial handshake with Twilio's signaling server rather than sending a request to a different endpoint
- IceServers are now localized to your Participant's region rather than using Global Low Latency routing
- The SDK no longer depends on `ecs.us1.twilio.com:443`
API Changes
- The following `IceOptions` properties are deprecated and setting them will have no effect.
- `IceOptions.abortOnIceServersTimeout`
- `IceOptions.iceServersTimeout`
Bug Fixes
- Fixed a bug where IceServers might not be fetched on a dual-stack device where the IPv6 …
> Update to Video Android 5.9.0

- build.gradle
* Programmable Video Android SDK 5.10.1 [[bintray]](https://bintray.com/twilio/releases/video-android/5.10.1), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.10.1/)
Bug Fixes
- Fixed a memory corruption crash that occurs when recovering from a media server failure in Group Rooms.
Known issues
> Update to Video Android 5.10.1

- .circleci/config.yml
- build.gradle
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
Promotes 0.4.0 to the first stable release of this library.
`UseContainerSupport` is now used in place of the `UseCGroupMemoryLimitForHeap` JVM argument since it is no longer supported in the latest Java 11 docker image.
> Upgrade to AudioSwitch 1.0.0

- .circleci/config.yml
- build.gradle
- exampleVideoInvite/README.md
- exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/notify/api/TwilioSDKStarterAPI.java
* Programmable Video Android SDK 5.10.2 [[bintray]](https://bintray.com/twilio/releases/video-android/5.10.2), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.10.2/)
Bug Fixes
- Fixed a bug on devices with more than two cameras where after `CameraCapturer.switchCamera(...)` completes, `CameraCapturer.getCameraSource()` would return an incorrect value. [#548](https://github.com/twilio/video-quickstart-android/issues/548)
Known issues
Size Report
| x86             | 6MB …
> Update to Video Android 5.10.2

- build.gradle
* Programmable Video Android SDK 5.11.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.11.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.11.0/)
Bug Fixes
- Set the default values of `AudioOptions` properties to match the default WebRTC values.
Known issues
Size Report
| x86             | 6MB             |
| x86_64          | 6.1MB           |
| armeabi-v7a     | 4.8MB           |
| arm64-v8a       | 5.7MB           |
| universal       | 21.9MB …
> Update to Video Android 5.11.0

- build.gradle
Enhancements
- Upgraded Kotlin to `1.4.0`.
- Improved the Bluetooth headset connection and audio change reliability by registering the `BluetoothHeadset.ACTION_CONNECTION_STATE_CHANGED` and `BluetoothHeadset.ACTION_AUDIO_STATE_CHANGED` intent actions instead of relying on `android.bluetooth.BluetoothDevice` and `android.media.AudioManager` intent actions.
- The context provided when constructing `AudioSwitch` can now take any context. Previously the `ApplicationContext` was required.
Bug Fixes
- Added the internal access modifier to the `SystemClockWrapper` class since it is not meant to be exposed publicly.
- Passed CI.
- Manually validated on a Huawei P30 Lite.
> Upgrade AudioSwitch to 1.0.1

- build.gradle
* Programmable Video Android SDK 5.11.1 [[bintray]](https://bintray.com/twilio/releases/video-android/5.11.1), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.11.1/)
Bug Fixes
- Fixed an SCTP related WebRTC security vulnerability detailed [here](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-6514).
Known issues
Size Report
| x86             | 6MB             |
| x86_64          | 6.1MB           |
| armeabi-v7a     | 4.8MB           |
| arm64-v8a       | 5.7MB …
> Update to Video Android 5.11.1

- .circleci/config.yml
- build.gradle
* Programmable Video Android SDK 4.4.1 [[bintray]](https://bintray.com/twilio/releases/video-android/4.4.1), [[docs]](https://twilio.github.io/twilio-video-android/docs/4.4.1/)
Bug Fixes
- Fixed an SCTP related WebRTC security vulnerability detailed [here](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-6514).
Known issues
- The SDK is not side-by-side compatible with other WebRTC based libraries …
> Update to Video Android 4.4.1

- build.gradle
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
Enhancements
- Added a constructor parameter named `preferredDeviceList` to configure the order in which audio devices are automatically selected and activated when `selectedAudioDevice` is null.
```kotlin
val audioSwitch = AudioSwitch(application, preferredDeviceList = listOf(Speakerphone::class.java, BluetoothHeadset::class.java))
```
- Updated `compileSdkVersion` and `targetSdkVersion` to Android API version `30`.
> Upgrade AudioSwitch to 1.1.0

- build.gradle
* Programmable Video Android SDK 5.13.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.13.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.13.0/)
Maintenance
- Added `VideoCapturer#setSurfaceTextureHelper`. This method enables SDK provided video capturers to capture to a surface texture using a public API rather than an internal method. While this method is public, capturing to a surface texture is currently only supported with `Camera2Capturer`, and `ScreenCapturer`. Capturing to a surface texture will be enabled in a future release.
Bug Fixes
- Fixed a race condition that could cause a crash or unnecessary web socket signaling reconnection.
- Fixed a bug where private IP address was not masked properly while publishing insights event.
Known issues
- …
> Update to 5.13.0

- build.gradle
- exampleAdvancedCameraCapturer/src/main/java/com/twilio/video/examples/advancedcameracapturer/AdvancedCameraCapturerActivity.kt
- exampleCustomVideoSink/src/main/java/com/twilio/video/examples/customvideosink/CustomVideoSinkVideoActivity.kt
- exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
- quickstart/src/main/java/com/twilio/video/quickstart/util/CameraCapturerCompat.java
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/CameraCapturerCompat.kt
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
* Programmable Video Android SDK 6.0.0-preview3 [[bintray]](https://bintray.com/twilio/releases/video-android/6.0.0-preview3), [[docs]](https://twilio.github.io/twilio-video-android/docs/6.0.0-preview3/)
* Added `useDtx` parameter for constraining bitrate while using Opus codec. `useDtx` is enabled by default.
Disabling `useDtx` will result in higher bitrate for silent audio while using Opus codec.
* `OpusCodec` class has a new constructor that takes `useDtx` as an input `OpusCodec(boolean useDtx)`. Use this to explicitly enable or disable DTX.
* Removed `IceOptions.abortOnIceServersTimeout` and `IceOptions.iceServersTimeout`.
* Removed `CameraCapturer.CameraSource`. `CameraCapturer` instances are now created using a camera ID as a `String`. You can use …
> Update to 6.0.0-preview3

- build.gradle
* Programmable Video Android SDK 6.0.0-beta1 [[bintray]](https://bintray.com/twilio/releases/video-android/6.0.0-beta1), [[docs]](https://twilio.github.io/twilio-video-android/docs/6.0.0-beta1/)
* Added the `ParticipantState` enumeration.
* Added the `getState()` method to `Participant`.
* Added new callbacks `onParticipantReconnecting` and `onParticipantReconnected` to `Room.Listener`. These callbacks will be raised when a `RemoteParticipant` is attempting to reconnect to a room due to a signaling network interruption. NOTE: It can take up to 15 seconds for our signaling backend to detect that a RemoteParticipant's connection has been disrupted due to a network degradation or handoff.
* Removed the `RemoteParticipant.isConnected()` method in favor of `Participant.getState()`.
Size Report …
> Update to 6.0.0-beta1

- exampleCustomAudioDevice/src/main/java/com/twilio/video/examples/examplecustomaudiodevice/FileAndMicAudioDevice.kt
Check audio record is initialized before calling startRecording API.
> Check audio record is initialized before calling startRecording API

- build.gradle
- quickstartKotlin/build.gradle
- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
Used ktx library from Video Android 6.1.0 release.
As part of this release, we have created a new Kotlin Extensions Library! This library provides a set of convenience functions and [extensions](https://kotlinlang.org/docs/reference/extensions.html) that provide Kotlin developers with a more idiomatic programming experience.
Below is a list of all of the extension APIs that are now available:
* `AudioOptions.kt`
* `BandwidthProfileOptions.kt`
* `ConnectOptions.kt`
* `DataTrackOptions.kt`
* `IceOptions.kt`
* `LocalAudioTrack.kt`
* `LocalDataTrack.kt`
* `LocalVideoTrack.kt`
* `Video.kt`
* `VideoBandwidthProfileOptions.kt`
To get started using this library, replace `implementation com.twilio:video-android:6.0.0` with `implementation com.twilio:video-android-ktx:6.1.0` in your application's …
> VAKTX-17: Use ktx library from Video Android 6.1.0 release

- build.gradle
* Programmable Video Android SDK 6.2.0 [[bintray]](https://bintray.com/twilio/releases/video-android/6.2.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/6.2.0/)
* Programmable Video Android SDK KTX 6.2.0 [[bintray]](https://bintray.com/twilio/releases/video-android-ktx/6.2.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/ktx/6.2.0/)
* Updated the SDK to Android Gradle Plugin 4.1.1
* Removed `tvi.webrtc.NetworkMonitor` and `tvi.webrtc.NetworkMonitorAutoDetect` from the `libwebrtc.jar` since they are unused by the SDK.
Size Report
| x86             | 5.5MB           |
| x86_64          | 5.5MB           |
| armeabi-v7a     | 4.1MB           |
| arm64-v8a       | 5.2MB           |
| …
> Update video sdk to 6.2.0

- build.gradle
* Programmable Video Android SDK 5.14.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.14.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.14.0/)
Enhancements
- `isRecording()` API now accurately reflects the current recording state of the `Room`. In the previous versions of the SDK, `isRecording()` could return false positives. The `onRecordingStarted(...)` and `onRecordingStopped(...)` callbacks will now be invoked when recording for at least a single track in the `Room` has started and stopped respectively.
Maintenance
* Removed `tvi.webrtc.NetworkMonitor` and `tvi.webrtc.NetworkMonitorAutoDetect` from the `libwebrtc.jar` provided by the SDK.
Known issues
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by …
> Update video android to 5.14.0

- build.gradle
* Programmable Video Android SDK 6.2.1 [[bintray]](https://bintray.com/twilio/releases/video-android/6.2.1), [[docs]](https://twilio.github.io/twilio-video-android/docs/6.2.1/)
* Fixed a crash that occurred while using either the `CameraCapturer` or `Camera2Capturer`, switching from the front camera to the back camera, and toggling the camera flash.
* Publishing multiple tracks with the same name results in a crash if network quality is enabled. To avoid this, use unique names for each track in the `Room`.
Size Report
| x86             | 5.5MB           |
| x86_64          | 5.5MB           |
| armeabi-v7a     | 4.1MB           |
| arm64-v8a       | 5.2MB           |
| universal       | 19.6MB          |
> Update video android to 6.2.1

- build.gradle
Move mavenCentral() above jcenter() in the project level build.gradle repositories block.
> VIDEO-4537: Move mavenCentral() above jcenter()

- build.gradle
- Programmable Video Android SDK 6.3.0 [Maven Central](https://search.maven.org/artifact/com.twilio/video-android/6.3.0/aar), [Docs](https://twilio.github.io/twilio-video-android/docs/6.3.0/)
- Programmable Video Android SDK KTX 6.3.0 [Maven Central](https://search.maven.org/artifact/com.twilio/video-android-ktx/6.3.0/aar), [Docs](https://twilio.github.io/twilio-video-android/docs/ktx/6.3.0/)
- 100 Participant Group Rooms Pilot Program: A Group Room created with max participants greater than 50 is structured to support a small number of presenters and a large number of viewers. It has the following behavioral differences compared to regular Group Rooms:
- The `RoomListener.onParticipantConnected()` callback method is invoked when a `RemoteParticipant` connects to the Room and publishes at …
> Consume latest video android 6.3.0

- build.gradle
* Fixed a crash (see stacktrace below) that sometimes occurs on Pixel devices when decoding VP8 video streams.
```
java.lang.IllegalArgumentException: Texture width must be positive, but was 0
FATAL EXCEPTION: AndroidVideoDecoder.outputThread
Process: com.twilio.video.test, PID: 13001
java.lang.IllegalArgumentException: Texture width must be positive, but was 0
at tvi.webrtc.SurfaceTextureHelper.setTextureSize(SurfaceTextureHelper.java:256)
at tvi.webrtc.AndroidVideoDecoder.deliverTextureFrame(AndroidVideoDecoder.java:432)
at tvi.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:407)
at tvi.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:369)
```
* Fixed a bug that could cause a crash when changing log level to Trace at runtime.
> …
> Video Android 6.3.1

- build.gradle
Update Android Video to version 6.4.1
* Fixed a crash when `maxTracks` or `renderDimensions` is set and a sink is added for a `RemoteVideoTrack`.
> Use Video Android 6.4.1

- README.md
- build.gradle
- The SDK now supports audio only rooms and added two error codes, ROOM_AUDIO_ONLY_FLAG_NOT_SUPPORTED_EXCEPTION (53124) & TRACK_TRACK_KIND_NOT_SUPPORTED_EXCEPTION (53125).
- Improved reconnection time after network connectivity disruptions.
- As of 6.0.0 of the SDK, hardware video encoding doesn't publish all of the three simulcast layers when VP8 simulcast is enabled on Android.
This affects Video Content Preferences from working properly for subscribing video participants since the feature requires all three simulcast layers to switch between.
Our team is working on a fix for this, but the feature does work when VP8 simulcast is used to publish video from participants using the Javascript or iOS SDKs.
- Video Content Preferences might prefer larger video than needed when device …
> Use Video Android 7.0.2

- README.md
- build.gradle
* Programmable Video Android SDK 7.0.3 [[Maven Central]](https://search.maven.org/artifact/com.twilio/video-android/7.0.3/aar), [[docs]](https://twilio.github.io/twilio-video-android/docs/7.0.3/)
* Programmable Video Android KTX SDK 7.0.3 [[Maven Central]](https://search.maven.org/artifact/com.twilio/video-android-ktx/7.0.3/aar), [[docs]](https://twilio.github.io/twilio-video-android/docs/ktx/7.0.3/)
- Added error code definition `PARTICIPANT_SESSION_LENGTH_EXCEEDED_EXCEPTION`.
- Fixed a bug where if an exception occurs when connecting to a Room, the Room instance could leak and setting a custom audio device could fail.
- Fixed a bug where media could incorrectly be detected as not flowing after the network connectivity changes.
- As of 6.0.0 of the SDK, hardware video encoding doesn't …
> Consume Video Android SDK 7.0.3

- .circleci/config.yml
Circle CI has deprecated the `circleci/android` docker images, this PR updates our CI integration to use a suitable new `cimg/android` image instead.
> Replace obsolete circleci docker image

- quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
Issues:
#680 #712 
Changes:
- Should not update status text onResume if Room.State.DISCONNECTED
- Should create video and audio tracks if permissions have been previously already granted.
> VIDEO-12826 - incorrect status onResume, crash when already granted permissions

- exampleScreenCapturer/build.gradle
- exampleScreenCapturer/src/main/AndroidManifest.xml
- exampleScreenCapturer/src/main/java/com/twilio/video/examples/screencapturer/ScreenCapturerActivity.java
Fixed bug with Screen Capturer quickstart where it would fail on Android 34.
> Fixed bug on android 34

- README.md
- exampleScreenCapturer/src/main/java/com/twilio/video/examples/screencapturer/ScreenCapturerActivity.java
Starting from API 34 it is required for user to consent for each MediaProjection capture session.
Adding screen capture permission each time screen share is selected and when orientation is changed on device rotation.
Issue #753 
[Link to Android changes](https://developer.android.com/about/versions/14/behavior-changes-14#media-projection-consent)
> Fix screen share SecurityException for API level 34 and above
