app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/twilio/conversations/quickstart/activity/ConversationActivity.java
app/src/main/res/menu/quickstart_menu.xml
app/src/main/res/values/strings.xml
build.gradle

Providing updates required for api changes made to Twilio Common Android and Conversations. In addition, I added a log out button that demonstrates how to properly dispose of the Conversations SDK

Update to 0.9.+

---

README.md
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
quickstart/build.gradle
quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java

Highlights:
1. Removing AccessManager
2. Release fixes emulator issues. Should resolve #31

Updating examples for 1.0.0-beta2 release

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
quickstart/build.gradle

This PR contains latest release and should resolve #47

Updates to 1.0.0-beta6 release

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
quickstart/build.gradle
quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java

Updates all modules for 1.0.0-beta7.
- Improved docs for `LocalMedia#addAudioTrack`
- Should resolve #53

Update to 1.0.0-beta7

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
quickstart/build.gradle
quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java

See [1.0.0-beta8 Changelog](https://www.twilio.com/docs/api/video/changelogs/android#100-beta8-february-8-2017) for further details on release
Fixes #54

Updates for 1.0.0-beta8 release

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
quickstart/build.gradle

Including content from [1.0.0-beta12 changelog](https://www.twilio.com/docs/api/video/changelogs/android#100-beta12-march-14-2017).
Improvements
- Made `VideoClient` an abstract class.
- We've begun formalizing our error codes. They are divided up into Signaling (530xx), Room (531xx), Participant (532xx), Track (533xx), Media (534xx), Configuration (535xx), and Access Token (201xx) subranges. Instances of `TwilioException` will now carry a numeric code belonging to one of these ranges, an error message, and an optional error explanation.
- Implemented a policy for applying `VideoConstraints` . Adding a `LocalVideoTrack` with no constraints, results in `LocalMedia` applying a set of default constraints based on the closest supported `VideoFormat` to 640x480 at 30 FPS. Adding a …

Updates for 1.0.0-beta12 release

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
quickstart/build.gradle

Included from [1.0.0-beta14 changelog](https://www.twilio.com/docs/api/video/changelogs/android#100-beta14-march-28-2017)
Improvements
- Simplified internal data structures that populate `StatsReport`.
Bug Fixes
- Fixed teardown crash that occurred in component that fetches ice servers.

Updates to 1.0.0-beta14 release

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
quickstart/build.gradle
quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java

Improvements
- Upgraded to WebRTC 57.
- Renaming `VideoClient` class to `Video`.

Updates for 1.0.0-beta15 release

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoCapturer/src/main/java/com/twilio/video/examples/customcapturer/ViewCapturer.java
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
quickstart/build.gradle

- Added enum VideoFrame.RotationAngle to ensure VideoFrame objects are constructed with valid orientation values.
- Updated CameraCapturer to be powered by latest WebRTC camera capturer.
- Updated CameraCapturer to allow scheduling a picture to be taken while the capturer is not running.
- Reverted decoding from surface textures. This revert should fix problems for custom VideoRenderer receiving null YUV data for VideoTrack #93 
- On Nexus 9 device, intermittent high decoding times results in delayed video. #95

Updates for 1.0.0-beta16 release

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
quickstart/build.gradle
quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java

We've promoted 1.0.0-beta17 to 1.0.0 as our first General Availability release.

Updates for 1.0.0 Release

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
quickstart/build.gradle

Bug Fixes
- Backported fix for Chromium bug [679306](https://codereview.webrtc.org/2879073002).

Update to 1.0.2

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
exampleVideoInvite/build.gradle
quickstart/build.gradle

Improvements
- Improved safety of asynchronous operations in native core.

Update to 1.2.1

---

exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
exampleVideoInvite/build.gradle
quickstart/build.gradle

Features
- Added static method `CameraCapturer.isSourceAvailable` that validates if a camera source is 
available on the device. This method is used when creating a `CameraCapturer` instance and when
calling `CameraCapturer#switchCamera` to validate that a source can be used for capturing frames.
Improvements
- Added javadoc to `Participant.Listener`, `ScreenCapturer.Listener`, `VideoCapturer.Listener`, 
and `VideoRenderer.Listener`. 
Bug Fixes
- Fixed a bug where multiple participants adding/removing tracks at the same time was not handled 
properly.

Update to 1.3.0 release

---

build.gradle
exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
exampleVideoInvite/build.gradle
quickstart/build.gradle

I've wanted to do this for a while. This PR sets all versions in top level `build.gradle`. I validated that changing values in top level is reflected in next build.

Set versions in build script

---

build.gradle
exampleAdvancedCameraCapturer/build.gradle
exampleCustomVideoCapturer/build.gradle
exampleCustomVideoRenderer/build.gradle
exampleScreenCapturer/build.gradle
exampleVideoInvite/build.gradle
quickstart/build.gradle

Same PR #157 but for the `2.0` branch.

Set versions buildscript

---

README.md
build.gradle
exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java
quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java

Improvements
- Upgraded to Android Oreo from Nougat 
- Fixed crash disconnecting from `Room` that has not connected #116
- Fixed NPE in in addParticipantVideo #151 
- Updated requestAudioFocus for Android O
- Updated target SDK, support library, and build tools for Android O
- Get available default camera source

1.3.2 Release

---

README.md
build.gradle
quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java

Quickstart Improvements
- Fixed bug moving local video track to primary view
---
SDK Improvements
- Improved threading contract.

1.3.5 Release

---

exampleDataTrack/src/main/java/com/twilio/video/examples/datatrack/DataTrackActivity.java
exampleDataTrack/src/main/java/com/twilio/video/examples/datatrack/MotionMessage.java

Breakdown
- Normalize drawing coordinates
- Send coordinates as doubles instead of strings

Update DataTrack Example

---

exampleVideoInvite/src/main/res/layout/content_video.xml
quickstart/src/main/res/layout/content_video.xml

Update primary video to use wrap_content

---

build.gradle

Improvements
- Added version to javadoc title, header, and bottom.

Update to 1.3.9

---

README.md
build.gradle

Improvements
- Added version to javadoc title, header, and bottom.
- `LocalParticipant` throws `IllegalArgumentException` when attempting to publish or unpublish
a released `Track`.
Bug Fixes
- Fixed crash disconnecting from a `Room` before being connected.

2.0.0-preview7 Updates

---

build.gradle

Improvements
- Refactor internal reference counting of internal MediaFactory.
Bug Fixes
- Don't publish Ice Candidate stats unless an active pair is present.

Update to 1.3.10

---

build.gradle

Improvements
- Refactor internal reference counting of internal MediaFactory.
Bug Fixes
- Don't publish Ice Candidate stats unless an active pair is present.

Update to 2.0.0-preview9

---

build.gradle

Improvements
- Updated `targetSdkVersion` to 27
- Updated `buildToolsVersion` to 27.0.3
- Updated Android Gradle plugin to to 3.0.1

Update to Video Android 1.3.11

---

build.gradle

Improvements
- Updated `targetSdkVersion` to 27
- Updated `buildToolsVersion` to 27.0.3
- Updated Android Gradle plugin to to 3.0.1

2.0.0-beta1

---

README.md

Adopting same branching conventions found on [Video iOS Quickstart](https://github.com/twilio/video-quickstart-swift).

Update README notice about 2.x branch moving to master

---

README.md

Update master README for 2.x APIs.

Update master branch README for 2.x APIs

---

build.gradle

Bug Fixes
- Fixed crash when calling Room#disconnect() twice. #255

Update to 2.0.0-beta2

---

build.gradle

Bug Fixes
- Fixed crash when calling Room#disconnect() twice. #255

Update to 1.3.13

---

build.gradle

Improvements
- Improved internal logic for retrieving ice servers and resolving outbound DNS.
Bug Fixes
- Fixed a bug where onDisconnected was not getting invoked due to a race condition between a network handover and a user initiated disconnect call.

1.3.14 Release

---

build.gradle

Bug Fixes
- Fixed issue where onDisconnected was not called when completing a Room using the REST API. #277

Update to 2.0.0-beta5

---

build.gradle

We've promoted `2.0.0-beta5` to `2.0.0` as our first General Availability release.

Update to 2.0.0

---

README.md

Just a little house cleaning for 2.0. Nice job on the release Android team!
The changes are similar to [video-quickstart-swift](https://github.com/twilio/video-quickstart-swift).

Update Readme header note and docs links for 2.x.

---

build.gradle

Improvements
- Updated Android Gradle Plugin to 3.1.1.
Bug Fixes
- Relaxed state check in CameraCapturer when stopCature is called and a camera closed event is
not received.

Update to Video Android 2.0.2

---

build.gradle

Improvements
- Updated Room.Listener documentation to provide more clarity about when onRecording callbacks are received.

Upgrade to 2.1.1

---

quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt

This PR contains an Android Studio suggested improvement to a lambda expression. Not high priority. Trying out Android development from a Windows computer 😲

Improve kotlin quickstart lambda expression

---

build.gradle

Features
- Added flag to IceOptions `abortOnIceServerTimeout` that tells the client whether to continue or abort connecting to a Room when Ice fails to connect.
- Added parameter to IceOptions `iceServersTimeout` that allows control of the timeout period when trying to retrieve Ice servers.
- Added `VideoTextureView`. `VideoTextureView` is similar to `VideoView` but subclasses `TextureView` instead of `SurfaceView`. Unlike SurfaceView, TextureView does not create a separate window but behaves as a regular View. This key difference allows a TextureView to be moved, transformed, animated, etc. For more see the [TextureView documentation](https://developer.android.com/reference/android/view/TextureView.html). If you were previously using [this …

Update to 3.0.0-preview2

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

This PR updates all versions to latest.
- Ran all modules locally

Update versions for Android Studio 3.2

---

README.md

Update `README.md` to include warning about WebRTC echo canceler on Pixel 3. 
WebRTC bug report: https://bugs.chromium.org/p/webrtc/issues/detail?id=10386

Provide warning / known issue when using WebRTC echo canceler

---

quickstart/src/main/java/com/twilio/video/quickstart/activity/SettingsActivity.java
quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
quickstart/src/main/res/xml/settings.xml
quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/SettingsActivity.kt
quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
quickstartKotlin/src/main/res/xml/settings.xml

This PR adds a toggle for automatic subscription in settings.

GSDK-1870: Add toggle for automatic subscription in kotlin and java quickStart

---

build.gradle

- Updated video dependency to 5.0.0-beta4
- Removed unused encoding parameters variable that was causing a NullPointerException.

Update android video sdk to 5.0.0-beta4

---

quickstart/src/main/res/menu/menu_video_activity.xml
quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
quickstartKotlin/src/main/res/menu/menu.xml
quickstartKotlin/src/main/res/values/strings.xml

Fixes #466 by providing the status of the speaker phone in the menu item of the quickstart and quickstartKotlin modules

Update menu item with speaker status

---

exampleAdvancedCameraCapturer/proguard-rules.pro
exampleCustomVideoCapturer/proguard-rules.pro
exampleCustomVideoRenderer/proguard-rules.pro
exampleDataTrack/proguard-rules.pro
exampleScreenCapturer/proguard-rules.pro
quickstart/proguard-rules.pro
quickstartKotlin/proguard-rules.pro

Changed webrtc package name in proguard file to fix release crash.

Change webrtc package name in proguard file to fix release crash

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
quickstart/build.gradle
quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
quickstart/src/main/res/drawable/ic_bluetooth_white_24dp.xml
quickstart/src/main/res/drawable/ic_headset_mic_white_24dp.xml
quickstart/src/main/res/menu/menu_video_activity.xml
quickstart/src/main/res/values/strings.xml
quickstartKotlin/build.gradle
quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt
quickstartKotlin/src/main/res/drawable/ic_bluetooth_white_24dp.xml
quickstartKotlin/src/main/res/drawable/ic_headset_mic_white_24dp.xml
quickstartKotlin/src/main/res/menu/menu.xml
quickstartKotlin/src/main/res/values/strings.xml

This PR uses [AudioSwitch](https://bintray.com/twilio/releases/audioswitch), a new Android library for managing audio routing in real-time communication apps. Initial inspiration from the [Video Android Collaboration App PR](https://github.com/twilio/twilio-video-app-android/pull/80). See the screenshots below as a visualization, but library enables:
* Managing the audio focus when connecting and disconnecting from a room
* Enables users to select an audio device
* Monitors changes in audio devices and updates the UI accordingly.

Use AudioSwitch for Kotlin and Java Quickstart

---

build.gradle

Upgrade AudioSwitch library to 0.1.2

Upgrade AudioSwitch library to 0.1.2

---

build.gradle

Upgraded the AudioSwitch dependency to 0.1.4.
Enhancements
- AAR minification is now enabled for release artifacts.
Bug Fixes
- Fixed a bug where the audio output doesn't automatically route to a newly connected bluetooth headset.
- Fixed a bug where the selected audio device doesn't get routed back to the default audio device when an error occurs when attempting to connect to a headset.

Upgrade to AudioSwitch 0.1.4

---

build.gradle

Bug Fixes
- Disabled AAR minification to fix Android Studio issues such as getting stuck in code analysis and not being able to find declarations of AudioSwitch code.

Upgrade to audioswitch 0.1.5

---

build.gradle

* The SDK API docs now include documentation for classes defined in [tvi.webrtc](https://twilio.github.io/twilio-video-android/docs/6.0.0-beta2/tvi/webrtc/package-frame.html). For example, the `VideoCapturer` API docs will now provide a link to the base interface `tvi.webrtc.VideoCapturer`.
* `isRecording()` API now accurately reflects the current recording state of the `Room`. In the previous versions of the SDK, `isRecording()` could return false positives. The `onRecordingStarted(...)` and `onRecordingStopped(...)` callbacks will now be invoked when recording for at least a single track in the `Room` has started and stopped respectively.
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source …

Upgrade to video SDK 6.0.0-beta2

---

common/src/main/java/com/twilio/video/examples/common/VideoFrameKtx.kt

Fix bug when capturing bitmap from a texture. Fixes #592 
Validated these changes with both camera1 and camera2 capture

Fix bug when capturing bitmap from texture

---

build.gradle

Enhancements
- Updated the library to use Android Gradle Plugin 4.1.1
- Now published to MavenCentral

Upgrade audioswitch to 1.1.2

---

README.md

Fix stale video app link. Thanks to @IgorGanapolsky for pointing this out in #632 .

Fix stale video app link in readme

---

build.gradle

Consume the latest Video Android SDK release, 6.4.0.

Consume Video 6.4.0

---

README.md

The Testing Tools page is no longer available.

Add instructions for generating Access Tokens via the Twilio CLI.

---

build.gradle
exampleAdvancedCameraCapturer/src/main/AndroidManifest.xml
exampleAudioSink/src/main/AndroidManifest.xml
exampleCustomAudioDevice/src/main/AndroidManifest.xml
exampleCustomAudioDevice/src/main/java/com/twilio/video/examples/examplecustomaudiodevice/FileAndMicAudioDevice.kt
exampleCustomVideoCapturer/src/main/AndroidManifest.xml
exampleCustomVideoSink/src/main/AndroidManifest.xml
exampleDataTrack/src/main/AndroidManifest.xml
exampleScreenCapturer/src/main/AndroidManifest.xml
exampleVideoInvite/src/main/AndroidManifest.xml
quickstart/src/main/AndroidManifest.xml
quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java
quickstartKotlin/src/main/AndroidManifest.xml
quickstartKotlin/src/main/java/com/twilio/video/quickstart/kotlin/VideoActivity.kt

Updated Quickstart & Quickstart-Kotlin to use latest version of audio switch and to properly request for the necessary bluetooth permissions.
- [*] I acknowledge that all my contributions will be made under the project's license.

Updated Quickstart and Quickstart Kotliin for andorid 12

---

build.gradle

Upgraded the version of audioswitch

updated audioswitch

---

build.gradle

Updated the quickstart to use the latest version of the android video sdk.

VIDEO-8689 Updated android sdk to latest

---

README.md
build.gradle

Updated the Android SDK version to the latest, 7.1.0

VIDEO-9162 Updated Android SDK version

---

README.md
build.gradle

Updated android sdk version to 7.1.1

Updated android sdk version to 7.1.1

---

build.gradle

Updated audioswitch version to 1.1.5

VIDEO-10372 Updated audioswitch to 1.1.5

---

README.md
build.gradle

Updated to Twilio-Video-7.1.2 for android.

Updated android sdk version to 7.1.2

---

common/src/main/java/com/twilio/video/examples/common/VideoFrameKtx.kt

Discovered a minor memory leak as the result of a customer escalation, now fixed.

VIDEO-10677: Fixed a minor memory leak

---

README.md
build.gradle

Updated to point to the 7.3.o0 releas

VIDEO-10818: Update for 7.3.0 release

---

README.md
build.gradle

Updated the sdk version to 7.4.0

Updated SDK Version to 7.4.0

---

README.md
build.gradle
common/src/main/java/com/twilio/video/examples/common/VideoFrameKtx.kt

Updated SDK version to 7.6.1

---

build.gradle

Upgrade audioSwitch 1.1.8

---

build.gradle

Updated SDK version

---

build.gradle

Updated sdk version to 7.6.4

---

.circleci/config.yml
build.gradle
exampleAudioSink/lint-baseline.xml
exampleCustomAudioDevice/lint-baseline.xml
exampleDataTrack/lint-baseline.xml
exampleScreenCapturer/lint-baseline.xml
exampleVideoInvite/build.gradle
exampleVideoInvite/lint-baseline.xml
exampleVideoInvite/src/androidTest/java/com/twilio/video/examples/videoinvite/ExampleInstrumentedTest.java
gradle/wrapper/gradle-wrapper.properties
quickstart/lint-baseline.xml
quickstartKotlin/lint-baseline.xml

VBLOCKS-2908: Upgraded AGP to 8.3.1

---

README.md

Updated the EOL date on warning banner to reflect that the date has been pushed 2 years out.

VBLOCKS-2958: Updated EOL banner

---

build.gradle

Updated SDK and AudioSwitch version to 7.7.1

[VBLOCKS-3426] updated sdk version to 7.7.1

---

build.gradle

updated to auto-update patch versions

---

README.md

VBLOCKS-3584 - Removed EOL banner

---

build.gradle

Updated to use Video Android 7.8.0

[VBLOLCKS-4056] updated to video android 7.8.0

---

build.gradle

Updated to use the latest version 7.9.0

[VBLOCKS-5027] updated sdk version
